package main

import (
	"bytes"
	"fmt"
	"go/format"
	"path/filepath"
	"strconv"
)

// render emits the Go source of the operations table.
//
// The output is source rather than an embedded blob so that a reviewer can see, in
// the diff, that an upstream spec change turned an explode from true to false — the
// one change in this file that silently rewrites what a filter means. A blob would
// hide it.
func render(pkg, spec string, ops []operation) ([]byte, error) {
	var b bytes.Buffer

	fmt.Fprintf(&b, "// Code generated by tools/specgen from %s. DO NOT EDIT.\n\n", filepath.Base(spec))
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	fmt.Fprintf(&b, "// operations is every operation in the spec, sorted by operationId.\n")
	fmt.Fprintf(&b, "// Reach it through Operations, LookupOperation and OperationsByTag.\n")
	fmt.Fprintf(&b, "var operations = []Operation{\n")

	for _, op := range ops {
		renderOperation(&b, op)
	}

	fmt.Fprintf(&b, "}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		// Emitting Go that does not parse is a bug in this program, not in the spec.
		// Returning the unformatted source with the error is what makes it findable.
		return nil, fmt.Errorf("format the generated source: %w\n%s", err, b.Bytes())
	}
	return src, nil
}

func renderOperation(b *bytes.Buffer, op operation) {
	fmt.Fprintf(b, "\t{\n")
	fmt.Fprintf(b, "\t\tID:     %s,\n", quote(op.ID))
	fmt.Fprintf(b, "\t\tMethod: %s,\n", quote(op.Method))
	fmt.Fprintf(b, "\t\tPath:   %s,\n", quote(op.Path))

	renderStrings(b, "Tags", op.Tags)

	if op.Summary != "" {
		fmt.Fprintf(b, "\t\tSummary: %s,\n", quote(op.Summary))
	}
	if op.Description != "" {
		fmt.Fprintf(b, "\t\tDescription: %s,\n", quote(op.Description))
	}

	renderStrings(b, "Permissions", op.Permissions)

	if len(op.Params) > 0 {
		fmt.Fprintf(b, "\t\tParams: []Param{\n")
		for _, p := range op.Params {
			renderParam(b, p)
		}
		fmt.Fprintf(b, "\t\t},\n")
	}

	if op.HasBody {
		fmt.Fprintf(b, "\t\tHasBody: true,\n")
	}
	if op.BodyRequired {
		fmt.Fprintf(b, "\t\tBodyRequired: true,\n")
	}
	if op.SampleBody != "" {
		fmt.Fprintf(b, "\t\tSampleBody: %s,\n", quote(op.SampleBody))
	}
	if op.Deprecated {
		fmt.Fprintf(b, "\t\tDeprecated: true,\n")
	}

	fmt.Fprintf(b, "\t},\n")
}

func renderParam(b *bytes.Buffer, p param) {
	fmt.Fprintf(b, "\t\t\t{Name: %s, In: %s, Type: %s",
		quote(p.Name), paramIn(p.In), paramType(p.Type))

	if p.Item != "" {
		fmt.Fprintf(b, ", Item: %s", paramType(p.Item))
	}
	if p.Required {
		fmt.Fprintf(b, ", Required: true")
	}
	// Explode is only rendered for an array: it is what decides between
	// status=A&status=B and status=A,B, and it means nothing for a scalar.
	if p.Type == "array" && p.Explode {
		fmt.Fprintf(b, ", Explode: true")
	}
	if len(p.Enum) > 0 {
		fmt.Fprintf(b, ", Enum: []string{")
		for i, v := range p.Enum {
			if i > 0 {
				fmt.Fprintf(b, ", ")
			}
			fmt.Fprintf(b, "%s", quote(v))
		}
		fmt.Fprintf(b, "}")
	}
	if p.Description != "" {
		fmt.Fprintf(b, ", Description: %s", quote(p.Description))
	}

	fmt.Fprintf(b, "},\n")
}

func renderStrings(b *bytes.Buffer, field string, values []string) {
	if len(values) == 0 {
		return
	}

	fmt.Fprintf(b, "\t\t%s: []string{", field)
	for i, v := range values {
		if i > 0 {
			fmt.Fprintf(b, ", ")
		}
		fmt.Fprintf(b, "%s", quote(v))
	}
	fmt.Fprintf(b, "},\n")
}

// The generated names of the api package's parameter constants. They are spelled
// here rather than imported, because specgen must not import the package it writes
// into: a generated file that does not compile would then take specgen down with
// it, and the only way out would be to hand-edit the file it just broke.
func paramIn(in string) string {
	switch in {
	case "path":
		return "InPath"
	case "query":
		return "InQuery"
	case "header":
		return "InHeader"
	default:
		return quote(in)
	}
}

func paramType(t string) string {
	switch t {
	case "string":
		return "TypeString"
	case "integer":
		return "TypeInteger"
	case "number":
		return "TypeNumber"
	case "boolean":
		return "TypeBoolean"
	case "array":
		return "TypeArray"
	default:
		return quote(t)
	}
}

// quote renders a Go string literal. strconv.Quote escapes everything, including
// the newlines a sample body is full of — a raw backtick literal would read better
// and would break the day a description or a sample value contained a backtick.
func quote(s string) string { return strconv.Quote(s) }
